# Generated by Django 4.0.4 on 2022-05-25 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sponsor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'OTM',
                'verbose_name_plural': 'OTMs',
                'db_table': 'otm',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('student_type', models.CharField(choices=[('bakalavr', 'Bakalavr'), ('magistr', 'Magistr')], max_length=60)),
                ('otm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students_otm', to='student.otm')),
                ('sponsors', models.ManyToManyField(help_text='Sponsorlar', related_name='students_sponsors', to='sponsor.sponsor')),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
                'db_table': 'students',
            },
        ),
    ]
