# Generated by Django 4.0.4 on 2022-05-30 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsor', '0007_sponsorallocateamount'),
        ('student', '0003_alter_student_sponsors'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='allocated_amount',
            new_name='total_allocated_amount',
        ),
        migrations.RemoveField(
            model_name='student',
            name='sponsors',
        ),
        migrations.AddField(
            model_name='student',
            name='sponsors_allocated_amount',
            field=models.ManyToManyField(blank=True, help_text='Homiylar ajratgan summa', related_name='students_sponsors_allocate', to='sponsor.sponsorallocateamount'),
        ),
    ]
