# Generated by Django 4.0.4 on 2022-05-30 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_rename_allocated_amount_student_total_allocated_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='total_allocated_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
