# Generated by Django 4.0.4 on 2022-05-30 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_alter_student_total_allocated_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='total_allocated_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
