# Generated by Django 4.0.4 on 2022-05-25 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sponsor_type', models.CharField(choices=[('jismoniy shaxs', 'Jismoniy shaxs'), ('yuridik shaxs', 'Yuridik shaxs')], max_length=60)),
                ('full_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('contract_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('allocated_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('company_name', models.CharField(blank=True, help_text='Tashkilot nomi', max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Sponsor',
                'verbose_name_plural': 'Sponsors',
                'db_table': 'sponsor',
            },
        ),
    ]
