# Generated by Django 4.0.4 on 2022-05-25 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sponsor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sponsor',
            name='allocated_amount',
        ),
        migrations.RemoveField(
            model_name='sponsor',
            name='contract_amount',
        ),
    ]
