# Generated by Django 4.0.4 on 2022-05-25 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsor', '0003_sponsor_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsor',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='status',
            field=models.CharField(choices=[('1', 'pendding'), ('2', 'Inactive'), ('3', 'Deleted')], default=1, max_length=1),
        ),
    ]
