# Generated by Django 4.0.4 on 2022-05-25 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsor', '0004_sponsor_created_at_sponsor_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='status',
            field=models.CharField(choices=[('1', 'Pending'), ('2', 'Accepted'), ('3', 'Rejected')], default=1, max_length=1),
        ),
    ]
