# Generated by Django 4.0.4 on 2022-05-27 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sponsor', '0005_alter_sponsor_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sponsor',
            options={'ordering': ['-created_at'], 'verbose_name': 'Sponsor', 'verbose_name_plural': 'Sponsors'},
        ),
    ]
