# Generated by Django 4.0.4 on 2022-05-30 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sponsor', '0006_alter_sponsor_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='SponsorAllocateAmount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('sponsor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsor_allocate_amount', to='sponsor.sponsor')),
            ],
            options={
                'verbose_name': 'Sponsor allocate amount',
                'verbose_name_plural': 'Sponsor allocate amounts',
                'db_table': 'sponsor_allocate_amount',
                'ordering': ['-created_at'],
            },
        ),
    ]
